# Generated by Django 3.1.4 on 2020-12-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20201206_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes',
            name='is_dislike',
            field=models.BooleanField(default=False),
        ),
    ]
